# サイドカーパターンでFalcoのアラートをfalcosidekickで転送する
services:
  falco:
    image: falcosecurity/falco:0.32.2
    privileged: true
    volumes:
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - /etc:/host/etc:ro
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./falco.yaml:/etc/falco/falco.yaml:ro
    depends_on:
      - falcosidekick
  falcosidekick:
    image: falcosecurity/falcosidekick:2.26.0
    environment:
      - DEBUG=true
