# サイドカーパターンでコンテナのログをFluent Bitで収集する
services:
  app:
    image: ubuntu
    command:
      [
        'bash',
        '-c',
        'while :; do echo `date` >> /mnt/log/log.txt; sleep 1; done',
      ]
    volumes:
      - log:/mnt/log
  fluent-bit:
    image: fluent/fluent-bit:1.9.7
    command:
      [
        '/fluent-bit/bin/fluent-bit',
        '-i',
        'tail',
        '-p',
        'path=/mnt/log/log.txt',
        '-o',
        'stdout',
      ]
    volumes:
      - log:/mnt/log
    depends_on:
      - app

volumes:
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
